version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - "./db-data:/data/db"
  
  api:
    build: "../rm-comments-server"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
  fe:
    image: nginx
    restart: always
    ports: 
      - "3001:80"
    volumes:
     - "./fe-build:/usr/share/nginx/html:ro"
     - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - api
